const mongoose = require('mongoose');

const UserSchema = mongoose.Schema({
    staff_code:String,
    user_name:String,
    display_name:String,
    password:String,
    clear_text_password:String,
    is_active:String,
    first_name:String,
    last_name:String,
    local_lng_name:String,
    login_type:String,
    profile_picture:String,
    email:String,
    skype_address:String,
    department:String,
    title:String,
    staff_other_code:String,
    branch:String,
    date_of_birth:String,
    postal_code:String,
    country:String,
    state:String,
    city:String,
    address1:String,
    address2:String,
    address3:String,
    tel_country_idd:String,
    tel:String,
    mobile_country_idd:String,
    mobile_city_idd:String,
    mobile:String,
    fax_country_idd:String,
    fax_city_idd:String,
    fax:String,
    home_tel_country_idd:String,
    home_tel_city_idd:String,
    home_tel:String,
    two_auth_fg:String,
    two_auth_secret_key:String,
    login_times:String,
    pwd_update_date:String,
    last_login_time:String,
    is_changed_password:String,
    create_by:String,
    create_date:String,
    update_by:String,
    update_date:String,
    remark:String,
    last_lock_time:String,
    password_initialized:String,
    failed_login_time:String,
    is_locked:String,
    reminder_date:String,
    alert_email_fg:String,
    alert_notification_fg:String,
    alert_mpush_fg:String,
    enable_fg:String,
    time_zone:String

}, {
    timestamps: true
});

module.exports = mongoose.model('User', UserSchema);